name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'Enter the target of development'
        required: true
        default: 'stm32'
        options:
          - 'stm32'
          - 'esp32'
          - 'iMX'
          - 'iMX8m'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file .devcontainer/Dockerfile --tag my-image-name:$(date +%s)
